# -*- coding: utf-8 -*-
# Generated by Django source.11.14 on 2019-03-23 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_num', models.IntegerField()),
                ('course', models.CharField(max_length=20, verbose_name='课程名称')),
                ('school', models.CharField(max_length=20, verbose_name='学校')),
                ('teacher', models.CharField(max_length=20, verbose_name='主讲人')),
                ('stu_num', models.IntegerField(blank=True, null=True)),
                ('introduction', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(max_length=255, verbose_name='网址')),
                ('commend', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('mobile', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='手机')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='booklist',
            name='userinfos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bysj.UserInfo'),
        ),
    ]
