# -*- coding: utf-8 -*-
# Generated by Django source.11.14 on 2019-03-27 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysj', '0002_auto_20190323_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='school',
            field=models.CharField(default='x', max_length=32, verbose_name='学校'),
            preserve_default=False,
        ),
    ]
