# -*- coding: utf-8 -*-
# Generated by Django source.11.14 on 2019-03-27 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysj', '0003_userinfo_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(default='2019-source-source'),
            preserve_default=False,
        ),
    ]
