# -*- coding: utf-8 -*-
# Generated by Django source.11.14 on 2019-04-01 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysj', '0006_auto_20190328_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.EmailField(max_length=255, unique=True, verbose_name='用户名'),
        ),
    ]
