# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-04-22 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bysj', '0007_auto_20190401_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_liuyan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bysj.UserInfo')),
            ],
        ),
    ]
