# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-04-22 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysj', '0009_auto_20190422_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='annunciate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
