# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-04-26 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bysj', '0012_auto_20190423_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='join_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
