# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-05-05 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysj', '0013_booklist_join_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_liuyan',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
